### ISSUE TITLE
[dojo-unity] Create starter scaffold

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo-starter-unity#1]
This starter should be based on [Nethermind Starknet Unity](https://github.com/NethermindEth/starknet.unity) 

**Unity**
The RPC endpoints to include should mirror the @dojoengine/core npm package to keep consistency - https://github.com/dojoengine/dojo/blob/main/packages/core/src/provider/RPCProvider.ts

**Cairo**
It should include the [dojo-starter](https://github.com/dojoengine/dojo-starter) as a submodule and base example of this world, which is the simplest possible world.

**Readme**
It should include detailed instructions on how to get the example up and running quickly.

**Comment by gogo2464** [comment]
assign me to this issue please.


I plan to create uniffy-rs-csharp binding for dojo in order to create unity dojo bindings package.
